-- ============================================================
-- SETUP SUPABASE — XV Vianca Gabriela (confirmaciones)
-- Córtalo una vez en Supabase Dashboard → SQL Editor
-- ============================================================

-- 1) Tabla
create table public.confirmaciones (
  id bigint generated by default as identity primary key,
  invitado text not null,
  acompanante text not null default '',
  fecha timestamptz not null default now(),
  confirmado boolean not null default false,
  confirmado_en timestamptz,
  invitado_confirmado boolean not null default false,
  acompanante_confirmado boolean not null default false,
  invitado_norm text generated always as (
    regexp_replace(translate(lower(invitado), 'áéíóúüñ', 'aeiouun'), '\s+', '', 'g')
  ) stored
);

-- 2) Evita invitados duplicados (ignora mayúsculas, acentos y espacios)
create unique index confirmaciones_invitado_norm_uq
  on public.confirmaciones (invitado_norm);

-- 3) RLS activado
alter table public.confirmaciones enable row level security;

-- 4) Políticas
-- Público (la invitación): solo puede INSERTAR
create policy "publico_insert" on public.confirmaciones
  for insert to anon
  with check (true);

-- Recepcionista (con sesión): puede ver, actualizar y eliminar
create policy "autenticado_select" on public.confirmaciones
  for select to authenticated
  using (true);

create policy "autenticado_update" on public.confirmaciones
  for update to authenticated
  using (true) with check (true);

create policy "autenticado_delete" on public.confirmaciones
  for delete to authenticated
  using (true);
